/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yao_jnimd5_Md5Utils */

#ifndef _Included_com_example_yao_jnimd5_Md5Utils
#define _Included_com_example_yao_jnimd5_Md5Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yao_jnimd5_Md5Utils
 * Method:    getRandomNum
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_yao_jnimd5_Md5Utils_getRandomNum
  (JNIEnv *, jclass, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
